### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fakerybakery** [asigalov61/Allegro-Music-Transformer#4]
Hi, have you considered creating a text-to-speech framework to generate speech as well? Currently, there are very few open source options for high quality TTS (I'm thinking of Tortoise), and I was wondering if a similar approach could work for TTS. Thanks!

**Comment by asigalov61** [comment]
@fakerybakery Unfortunately, I deal only with Symbolic Music and autoregressive model/implementations. Audio and TTS is a completely different domain of AI which I am not very familiar with.
