### ISSUE TITLE
Installing Fluidsynth using conda on Windows

### ISSUE THREAD

**Issue by XarsEvandor** [asigalov61/Allegro-Music-Transformer#8]
Hello, I am trying to create a conda env with the requirements for this project but I have trouble installing fluidsynth, 
Is it not available on windows? Is there an alternative method? I would like to avoid using docker or notebooks as it would increase the complexity of my project by a lot.

If the dependency cannot be resolved, could you outline the points where it is used? I could create a custom implementation that uses a different utility.

Thank you for your time!

**Comment by asigalov61** [comment]
@XarsEvandor Yes, this is a common problem with conda and Windows...

Fluidsynth is the only solution at the moment. I do not know any other way, unfortunatelly.

But try these things:

1) Use !sudo apt install fluidsynth

2) If this does not work, try creating virtualenv first on conda and then installing again with sudo apt install.

Let me know if this helps.

Alex.

**Comment by asigalov61** [comment]
@XarsEvandor I am closing this for now since you seem to have figured it out :)
